name: Build

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: ['1.21']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
        cache: false

    - name: Install dependencies
      run: |
        go mod download
        go mod tidy

    - name: Run tests
      run: go test -v ./...

    - name: Run go vet
      run: go vet ./...

    - name: Build
      run: go build -v -ldflags="-s -w" -o burnmail${{ matrix.os == 'windows-latest' && '.exe' || '' }} .

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: burnmail-${{ matrix.os }}
        path: burnmail${{ matrix.os == 'windows-latest' && '.exe' || '' }}
